# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: HRC2 - Human-Robot Collaboration and Companionship Lab
description: Human-Robot Collaboration and Companionship (Hoffman) Lab at Cornell University
url: http://hrc2.io

markdown: redcarpet

redcarpet:
  extensions:
   - tables
   - no_intra_emphasis
   - autolink
   - superscript
   - strikethrough

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
